name: Deploy to Heroku

on:
  workflow_dispatch:
    inputs:
      app-name:
        description: Name for Heroku app
        required: true
      is-app-already-created:
        type: boolean
        description: App already created
        default: true
        required: true

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create app
        if: github.event.inputs.is-app-already-created != true
        uses: ./.github/actions/create-heroku-app
        with:
          app-name: ${{ github.event.inputs.app-name }}
          heroku-api-key: ${{ secrets.HEROKU_API_KEY }}
      - name: Deploy
        run: |
          heroku git:remote -a ${{ github.event.inputs.app-name }}
          git push heroku ${{ github.ref_name }}:master
